### ISSUE TITLE
dicom files without .dcm extension

### ISSUE THREAD

**Issue by jpcenteno80** [ZviBaratz/dicom_parser#14]
Sometimes I run into dicom files without the `.dcm` extension. As an enhancement, I thought you could check for the file type in the `series.py` file. However, it adds a requirement: `pip install python-magic`.

### series.py
```
...
import magic
...
def get_dcm_paths(self) -> GeneratorType:
    """
    Returns a generator of .dcm files within the provided directory path.

    Returns
    -------
    GeneratorType
        DICOM images (.dcm files) generator

    Raises
    ------
    FileNotFoundError
        No DICOM images found under provided directory
    """

    _, dcm_paths = peek(self.path.rglob("*.*")) # rglob all files
    if dcm_paths:
        # if the file is dicom, the magic call will output "application/dicom"
        dcm_paths = [p for p in dcm_paths if "dicom" in magic.from_file(str(p), mime=True)]
    if not dcm_paths:
        raise FileNotFoundError(EMPTY_SERIES_DIRECTORY)
    return dcm_paths
```

**Comment by ZviBaratz** [comment]
Hi @jpcenteno80, thank you for reporting and for proposing a solution! 
This certainly seems like a useful feature request, I'll try and come up with something sometime soon.

**Comment by ZviBaratz** [comment]
@jpcenteno80 I merged a PR to resolve the issue and will publish a new version today. If you're willing to validate that the update resolved your issue it would be appreciated :pray:

**Comment by jpcenteno80** [comment]
Thank you for the very clean fix. It works great: `series = Series(path, mime=True`) when the file does not end in `.dcm`. I am not sure how to do a "proper" validation of the merged PR, but your fix is working in my system and for my use case.

**Comment by ZviBaratz** [comment]
Glad to hear! Thank you for reporting and best of luck with your work.
