### ISSUE TITLE
Issue while trying to get image type

### ISSUE THREAD

**Issue by gregblt** [ZviBaratz/dicom_parser#8]
Hello! I just found out about this python library which seems really useful to get a summary of a dicom series

I encountered the following issue while trying to read the image type ( I tried series['ImageType'], series.get('ImageType') and series.get((0x0008, 0x0008)) ) :

Traceback (most recent call last):

  File "<ipython-input-70-3242b7f88aca>", line 1, in <module>
    series.get((0x0008, 0x0008))

  File "/opt/anaconda3/lib/python3.8/site-packages/dicom_parser/series.py", line 170, in get
    unique_values = set(values)

TypeError: unhashable type: 'list'

The value of this tag in my series is : [ORIGINAL\PRIMARY\OTHER]

**Comment by ZviBaratz** [comment]
Hi @gregblt, thank you for reporting this (and for your feedback!).
It seems I didn't account for the case of the returned data element values being unhashable. I'll try and publish the fix (should be something like `unique_values = set(tuple(values))`) in the next couple of days.

**Comment by gregblt** [comment]
I guess every item inside the `values` list that is a list will have to be a tuple instead. I am not an expert in Python so maybe there is a more pythonic way of writing this : 

```
        for i, val in enumerate(values):
            if(type(values[i]) is list):
                values[i] = tuple(values[i])
                
        unique_values = set(values)
```

Or that could be done earlier in the code by inserting tuples instead of lists when creating the `values` list (that's a lot of lists..!)

Best,

**Comment by ZviBaratz** [comment]
> I guess every item inside the `values` list that is a list will have to be a tuple instead. 

Indeed, I wasn't thinking :)

> I am not an expert in Python so maybe there is a more pythonic way of writing this :
> 
> ```
>         for i, val in enumerate(values):
>             if(type(values[i]) is list):
>                 values[i] = tuple(values[i])
>                 
>         unique_values = set(values)
> ```
> 

I think we would be better off with: 
```python
unique_values = set(tuple(value) for value in values)
```

> Or that could be done earlier in the code by inserting tuples instead of lists when creating the `values` list (that's a lot of lists..!)

Indeed, returning tuples might be a good idea. 

If you're interested in suggesting a PR please do feel free and welcome. Otherwise, I'll try and come up with something later today or tomorrow.

**Comment by ZviBaratz** [comment]
Hope the new release addresses your issue. To update:
```
pip install --upgrade dicom_parser
```
